#!/bin/bash
#
# Builds Docker image.
#
set -euo pipefail

DOCKER_USER="hkjn"
DOCKER_IMAGE="pki"

ARCH="$(uname -m)"
BUILD_DIR="$(mktemp -d)"

cp Dockerfile "$BUILD_DIR/"
cp -r configs/ "$BUILD_DIR/"
cp -r bin/ "$BUILD_DIR/"
# TODO(hkjn): Fix this special-casing to support different CPU
# architectures. Just call it hkjn/x86_64-alpine as well?
[[ $ARCH = "x86_64" ]] || {
  sed -i "s/FROM hkjn\//FROM hkjn\/$ARCH-/" "$BUILD_DIR/Dockerfile"
  DOCKER_IMAGE="$ARCH-$DOCKER_IMAGE"
}

TAG="$DOCKER_USER/$DOCKER_IMAGE"
docker build -t $TAG "$BUILD_DIR/"
NO_PUSH=${NO_PUSH:-""}
[[ "$NO_PUSH" ]] || docker push $TAG

