#!/bin/sh
#
# Generates CA cert/key and single key/cert.
#
HOST="$1"
echo "Generating CA key/cert and key/cert for $HOST in /certs.."
mkdir -p /certs/
cfssl gencert \
  -initca /etc/configs/ca-csr.json | cfssljson -bare /certs/ca
cfssl gencert \
  -hostname $HOST \
  -ca /certs/ca.pem \
  -ca-key /certs/ca-key.pem \
  -config /etc/configs/ca-config.json \
   /etc/configs/req-csr.json | cfssljson -bare /certs/$HOST